# Generated by Django 4.2.6 on 2023-11-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Languages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MoviesDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_name", models.CharField(max_length=200)),
                ("poster", models.ImageField(upload_to="movie_posters/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "UPCOMING"),
                            ("CURRENTLYPLAYING", "CURRENTLY PLAYING"),
                            ("RELEASED", "RELAESED"),
                        ],
                        default="UPCOMING",
                        max_length=20,
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(
                        related_name="movie_language", to="admin_dashboard.languages"
                    ),
                ),
            ],
        ),
    ]
