# Generated by Django 4.2.6 on 2023-11-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviesdetails",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="movie_posters/"),
        ),
    ]
