# Generated by Django 4.2.6 on 2023-11-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dashboard", "0002_alter_moviesdetails_poster"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moviesdetails",
            options={"ordering": ("id",)},
        ),
        migrations.AddField(
            model_name="moviesdetails",
            name="director",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="moviesdetails",
            unique_together={("movie_name", "director")},
        ),
    ]
