# Generated by Django 4.2.6 on 2023-12-17 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dashboard", "0002_rating_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
