# Generated by Django 4.2.6 on 2023-11-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dashboard", "0004_remove_moviesdetails_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviesdetails",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPCOMING", "UPCOMING"),
                    ("CURRENTLYPLAYING", "CURRENTLY PLAYING"),
                    ("RELEASED", "RELEASED"),
                ],
                default="UPCOMING",
                max_length=20,
            ),
        ),
    ]
