# Generated by Django 4.2.6 on 2023-10-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='auth_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
