# Generated by Django 4.2.6 on 2023-11-20 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentications", "0002_remove_userprofile_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestlocation",
            name="current_location",
        ),
    ]
