# Generated by Django 4.2.6 on 2023-10-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0008_remove_location_name_location_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='status',
        ),
        migrations.AddField(
            model_name='requestlocation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10),
        ),
    ]
