# Generated by Django 4.2.6 on 2023-10-17 11:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0009_remove_location_status_requestlocation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlocation',
            name='name',
        ),
        migrations.AddField(
            model_name='requestlocation',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestlocation',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='requestlocation',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestlocation',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestlocation',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
