# Generated by Django 4.2.6 on 2023-12-11 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentications", "0001_initial"),
        ("admin_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreenDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen_number", models.IntegerField(blank=True, null=True)),
                ("number_of_seats", models.IntegerField(blank=True, null=True)),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("column_count", models.IntegerField(blank=True, null=True)),
                ("ticket_rate", models.IntegerField()),
                ("is_approved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ShowDates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dates", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ShowTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TheareOwnerDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("phone", models.CharField(max_length=13, unique=True)),
                (
                    "alternative_contact",
                    models.CharField(blank=True, max_length=13, null=True, unique=True),
                ),
                ("id_number", models.CharField(max_length=100)),
                (
                    "id_proof",
                    models.ImageField(
                        blank=True, null=True, upload_to="owner_id_proof/"
                    ),
                ),
                ("address", models.TextField()),
                ("is_verified", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="theatreownerdetails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScreenSeatArrangement",
            fields=[
                (
                    "screen",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="theatre_dashboard.screendetails",
                    ),
                ),
                ("seating", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TheatreDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theatre_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("phone", models.CharField(max_length=13, unique=True)),
                (
                    "alternative_contact",
                    models.CharField(blank=True, max_length=13, null=True, unique=True),
                ),
                ("address", models.TextField()),
                ("num_of_screens", models.CharField(max_length=2)),
                ("certification", models.ImageField(upload_to="TheatreCertification/")),
                ("is_verified", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentications.location",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="theatreowner",
                        to="theatre_dashboard.theareownerdetails",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="screendetails",
            name="theatre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screen_details",
                to="theatre_dashboard.theatredetails",
            ),
        ),
        migrations.CreateModel(
            name="Shows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="admin_dashboard.languages",
                    ),
                ),
                (
                    "movies",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="admin_dashboard.moviesdetails",
                    ),
                ),
                (
                    "screen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="theatre_dashboard.screendetails",
                    ),
                ),
                (
                    "show_dates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="showdate",
                        to="theatre_dashboard.showdates",
                    ),
                ),
                (
                    "show_time",
                    models.ManyToManyField(
                        blank=True,
                        related_name="showtime",
                        to="theatre_dashboard.showtime",
                    ),
                ),
            ],
            options={
                "unique_together": {("language", "screen", "movies")},
            },
        ),
    ]
