# Generated by Django 4.2.6 on 2023-11-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theareownerdetails",
            name="id_proof",
            field=models.ImageField(blank=True, null=True, upload_to="owner_id_proof/"),
        ),
    ]
