# Generated by Django 4.2.6 on 2023-11-14 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0002_alter_theareownerdetails_id_proof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screendetails",
            name="theatre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screen_details",
                to="theatre_dashboard.theatredetails",
            ),
        ),
    ]
