# Generated by Django 4.2.6 on 2023-10-24 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theatre_dashboard', '0002_alter_theareownerdetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theareownerdetails',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='theareownerdetails',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='theareownerdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theatreowner', to=settings.AUTH_USER_MODEL),
        ),
    ]
