# Generated by Django 4.2.6 on 2023-11-14 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0003_alter_screendetails_theatre"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreenSeatArrangement",
            fields=[
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="theatre_dashboard.screendetails",
                    ),
                ),
                ("Seating", models.JSONField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("NONE", "WHITE"),
                            ("BOOKED", "WHITE"),
                            ("BOOKING", "GREEN"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="screendetails",
            name="seat_arrangement",
        ),
    ]
