# Generated by Django 4.2.6 on 2023-10-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_dashboard', '0005_theatredetails_screendetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatredetails',
            name='certification',
            field=models.CharField(max_length=100),
        ),
    ]
