# Generated by Django 4.2.6 on 2023-11-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0005_alter_screenseatarrangement_screen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="screenseatarrangement",
            old_name="Seating",
            new_name="seating",
        ),
        migrations.AlterField(
            model_name="screenseatarrangement",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[("NONE", "WHITE"), ("BOOKED", "WHITE"), ("BOOKING", "GREEN")],
                default="NONE",
                max_length=10,
                null=True,
            ),
        ),
    ]
