# Generated by Django 4.2.6 on 2023-11-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0007_screendetails_movies"),
    ]

    operations = [
        migrations.AddField(
            model_name="theatredetails",
            name="address",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
