# Generated by Django 4.2.6 on 2023-10-26 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0007_theareownerdetails_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theareownerdetails",
            name="id_number",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="theatredetails",
            name="alternative_contact",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="theatredetails",
            name="email",
            field=models.EmailField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="theatredetails",
            name="is_approved",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="theatredetails",
            name="is_loginned",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="theatredetails",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="theatreowner",
                to="theatre_dashboard.theareownerdetails",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="theatredetails",
            name="phone",
            field=models.CharField(default=1, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
