# Generated by Django 4.2.6 on 2023-11-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0008_theatredetails_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="screendetails",
            name="shows",
            field=models.ManyToManyField(blank=True, to="theatre_dashboard.shows"),
        ),
    ]
