# Generated by Django 4.2.6 on 2023-10-26 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theatre_dashboard', '0009_theareownerdetails_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theareownerdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theatreownerdetails', to=settings.AUTH_USER_MODEL),
        ),
    ]
