# Generated by Django 4.2.6 on 2023-11-17 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "admin_dashboard",
            "0003_alter_moviesdetails_options_moviesdetails_director_and_more",
        ),
        ("theatre_dashboard", "0009_shows_screendetails_shows"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name="screendetails",
            name="movies",
        ),
        migrations.RemoveField(
            model_name="screenseatarrangement",
            name="color",
        ),
        migrations.RemoveField(
            model_name="shows",
            name="time",
        ),
        migrations.AddField(
            model_name="shows",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shows",
            name="movies",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="admin_dashboard.moviesdetails",
            ),
        ),
        migrations.AddField(
            model_name="shows",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="screendetails",
            name="shows",
        ),
        migrations.AddField(
            model_name="shows",
            name="show_time",
            field=models.ManyToManyField(blank=True, to="theatre_dashboard.showtime"),
        ),
        migrations.AddField(
            model_name="screendetails",
            name="shows",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="theatre_dashboard.shows",
            ),
        ),
    ]
