# Generated by Django 4.2.6 on 2023-10-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_dashboard', '0010_alter_theareownerdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatredetails',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
