# Generated by Django 4.2.6 on 2023-10-26 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0011_theatredetails_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theatredetails",
            name="is_approved",
        ),
    ]
