# Generated by Django 4.2.6 on 2023-11-17 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0011_alter_showtime_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screendetails",
            name="shows",
        ),
        migrations.AddField(
            model_name="shows",
            name="screen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="theatre_dashboard.screendetails",
            ),
        ),
    ]
