# Generated by Django 4.2.6 on 2023-10-26 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0012_remove_theatredetails_is_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theatredetails",
            name="is_loginned",
        ),
    ]
