# Generated by Django 4.2.6 on 2023-11-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0014_alter_theareownerdetails_id_proof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theatredetails",
            name="certification",
            field=models.ImageField(upload_to="TheatreCertification/"),
        ),
    ]
