# Generated by Django 4.2.6 on 2023-11-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0015_alter_shows_movies"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowDates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dates", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="shows",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="shows",
            name="start_date",
        ),
        migrations.AddField(
            model_name="shows",
            name="dates",
            field=models.ManyToManyField(blank=True, to="theatre_dashboard.showdates"),
        ),
    ]
