# Generated by Django 4.2.6 on 2023-11-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0015_alter_theatredetails_certification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theatredetails",
            name="num_of_screens",
            field=models.CharField(max_length=2),
        ),
    ]
