# Generated by Django 4.2.6 on 2023-11-01 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0016_alter_theatredetails_num_of_screens"),
    ]

    operations = [
        migrations.RenameField(
            model_name="theatredetails",
            old_name="is_verified",
            new_name="is_approved",
        ),
    ]
