# Generated by Django 4.2.6 on 2023-11-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0017_rename_dates_shows_show_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shows",
            name="show_dates",
            field=models.ManyToManyField(
                blank=True, related_name="showdate", to="theatre_dashboard.showdates"
            ),
        ),
        migrations.AlterField(
            model_name="shows",
            name="show_time",
            field=models.ManyToManyField(
                blank=True, related_name="showtime", to="theatre_dashboard.showtime"
            ),
        ),
    ]
