# Generated by Django 4.2.6 on 2023-11-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0018_alter_shows_show_dates_alter_shows_show_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showtime",
            name="time",
            field=models.TimeField(max_length=100),
        ),
    ]
