# Generated by Django 4.2.6 on 2023-11-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0019_alter_showtime_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showtime",
            name="time",
            field=models.CharField(max_length=100),
        ),
    ]
