# Generated by Django 4.2.6 on 2023-11-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0020_alter_showtime_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screenseatarrangement",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="screendetails",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
