# Generated by Django 4.2.6 on 2023-11-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0021_remove_screenseatarrangement_is_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theatredetails",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
