# Generated by Django 4.2.6 on 2023-12-04 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("theatre_dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="theatre_dashboard.shows",
                    ),
                ),
                (
                    "theatre_screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="theatre_dashboard.screendetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tickets", models.JSONField()),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_dashboard.bookingdate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticketdetails",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_dashboard.bookingdetails",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="theatre_dashboard.showtime",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bookingdate",
            name="bookingtime",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_dashboard.bookingtime",
            ),
        ),
        migrations.AddField(
            model_name="bookingdate",
            name="showdate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="theatre_dashboard.showdates",
            ),
        ),
    ]
