# Generated by Django 4.2.6 on 2023-11-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketbooking",
            name="number_of_tickets",
        ),
        migrations.AddField(
            model_name="ticketbooking",
            name="tickets",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
