# Generated by Django 4.2.6 on 2023-12-05 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_dashboard", "0002_alter_bookingdate_bookingtime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookingdate",
            old_name="bookingtime",
            new_name="bookingdetails",
        ),
        migrations.RenameField(
            model_name="bookingtime",
            old_name="ticketdetails",
            new_name="bookingdetails",
        ),
    ]
