# Generated by Django 4.2.6 on 2023-12-04 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("theatre_dashboard", "0022_theatredetails_is_verified"),
        ("user_dashboard", "0002_remove_ticketbooking_number_of_tickets_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketbooking",
            name="booking_date",
        ),
        migrations.RemoveField(
            model_name="ticketbooking",
            name="show",
        ),
        migrations.RemoveField(
            model_name="ticketbooking",
            name="theatre_screen",
        ),
        migrations.AlterField(
            model_name="ticketbooking",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="BookingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="theatre_dashboard.shows",
                    ),
                ),
                (
                    "showdate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="theatre_dashboard.showdates",
                    ),
                ),
                (
                    "showtime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="theatre_dashboard.showtime",
                    ),
                ),
                (
                    "theatre_screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="theatre_dashboard.screenseatarrangement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticketbooking",
            name="ticketdetails",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_dashboard.bookingdetails",
            ),
            preserve_default=False,
        ),
    ]
