# Generated by Django 4.2.6 on 2023-12-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0022_theatredetails_is_verified"),
        ("user_dashboard", "0003_remove_ticketbooking_booking_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingdetails",
            name="showdate",
        ),
        migrations.RemoveField(
            model_name="bookingdetails",
            name="showtime",
        ),
        migrations.AddField(
            model_name="ticketbooking",
            name="showdate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="theatre_dashboard.showdates",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticketbooking",
            name="showtime",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="theatre_dashboard.showtime",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookingdetails",
            name="theatre_screen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="theatre_dashboard.screendetails",
            ),
        ),
    ]
