# Generated by Django 4.2.6 on 2023-12-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0001_initial"),
        (
            "user_dashboard",
            "0003_rename_bookingtime_bookingdate_bookingdetails_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingtime",
            name="bookingdetails",
        ),
        migrations.RemoveField(
            model_name="bookingtime",
            name="time",
        ),
        migrations.AddField(
            model_name="ticketbooking",
            name="bookingdetail",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_dashboard.bookingdetails",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticketbooking",
            name="time",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="theatre_dashboard.showtime",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ticketbooking",
            name="date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="theatre_dashboard.showdates",
            ),
        ),
        migrations.DeleteModel(
            name="BookingDate",
        ),
        migrations.DeleteModel(
            name="BookingTime",
        ),
    ]
