# Generated by Django 4.2.6 on 2023-12-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("theatre_dashboard", "0002_alter_shows_unique_together"),
        ("user_dashboard", "0004_remove_bookingtime_bookingdetails_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketbooking",
            name="bookingdetail",
        ),
        migrations.AddField(
            model_name="ticketbooking",
            name="show",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="theatre_dashboard.shows",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="BookingDetails",
        ),
    ]
