# Generated by Django 4.2.6 on 2023-12-06 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_dashboard", "0005_remove_ticketbooking_bookingdetail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketbooking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
